### PR TITLE
organize code.gov specific doc files

### PR DESCRIPTION
**Pull request by mvedataydin**
Solve issue #54

### CODE REVIEW

**Comment by saracope** [comment]
EEEeek, it looks like one of my teammates just added a new folder for meeting minutes. Can you move this to docs too? 😀 

https://github.com/GSA/code-gov/tree/master/CoPMeetingMins

**Comment by mvedataydin** [comment]
Yes of course, should i also add the new file in the folder to the list in README.md?

**Comment by saracope** [comment]
How about adding this to the files list too:

- CoPMeetingMins: folder containing the notes from our monthly Community of Practice meetings

**Comment by mvedataydin** [comment]
I added CoPMeetingMins to the listing in README.md, also sorry for multiple commits i am still learning contribution and made some mistakes :sweat_smile:

**Comment by saracope** [comment]
Thanks! I'll look at this today.

**Pull request merged**
